import type {
  PatientReport,
  RiskScore,
  ToothbrushTelemetry,
  VisionResult,
} from "@/lib/types/screening";
import {
  SCREENING_DISCLAIMER,
  VISUAL_FINDING_LABEL,
} from "@/lib/utils/riskUtils";

export interface PatientCommunicationInput {
  vision: VisionResult;
  risk: RiskScore;
  toothbrush: ToothbrushTelemetry;
}

/**
 * Patient Communication Agent
 *
 * Translates the technical screening output into a calm, plain-language
 * patient-facing report. Never claims confirmed cancer; always includes the
 * mandatory medical disclaimer.
 */
export async function runPatientCommunicationAgent(
  input: PatientCommunicationInput
): Promise<PatientReport> {
  const { vision, risk, toothbrush } = input;
  const findingLabel = VISUAL_FINDING_LABEL[vision.visualFinding].toLowerCase();
  const region =
    vision.suspectedRegion === "none" || vision.suspectedRegion === "unknown"
      ? "no specific region"
      : vision.suspectedRegion;

  let headline: string;
  let message: string;
  let nextStep: string;

  switch (risk.riskLevel) {
    case "Low":
      headline = "No strong oral cancer-like signs observed in this screening.";
      message =
        "No strong oral cancer-like visual sign was observed in this prototype screening. " +
        "Your reported risk factors are also limited.";
      nextStep =
        "Continue routine oral hygiene and repeat screening periodically. " +
        "Seek dental review if any new symptoms persist for more than 2 weeks.";
      break;
    case "Medium":
      headline = "Some signs or risk factors were noted — monitor closely.";
      message =
        "Some abnormal signs or risk factors were noted during this prototype screening. " +
        "This does not confirm any disease, but it warrants closer monitoring.";
      nextStep =
        "Monitor the area closely. Arrange a dental review if the lesion persists, worsens, " +
        "or lasts more than 2 weeks.";
      break;
    case "High":
      headline =
        "Oral cancer-like screening risk flag generated — follow-up recommended.";
      message =
        "An oral cancer-like screening risk flag was generated by the prototype based on the visual " +
        "finding and your reported risk factors. This is not a diagnosis.";
      nextStep =
        "Professional dental or oral medicine review is recommended. " +
        "A clinician referral packet has been prepared in the prototype dashboard.";
      break;
  }

  const whatWasObserved =
    vision.visualFinding === "normal"
      ? "The image showed tissue that looks within typical appearance for screening."
      : `The image showed ${findingLabel} at ${region}. ` +
        `Prototype-estimated oral cancer-like probability: ${(
          vision.oralCancerLikeProbability * 100
        ).toFixed(0)}%.`;

  const whyThisLevel =
    risk.topRiskDrivers.length > 0
      ? `Risk band assigned because of: ${risk.topRiskDrivers.join("; ")}.`
      : "Risk band assigned because no significant risk drivers were detected.";

  // Quality nudge for the patient.
  const qualityNudge =
    toothbrush.imageQualityScore < 0.5 || vision.imageQuality === "poor"
      ? " Note: image quality was limited — a rescan in better lighting may improve accuracy."
      : "";

  return {
    headline,
    message: message + qualityNudge,
    whatWasObserved,
    whyThisLevel,
    nextStep,
    disclaimer: SCREENING_DISCLAIMER,
  };
}
